### ISSUE TITLE
Young's module max value?

### ISSUE THREAD

**Issue by Bryan-Wong919** [XPandora/PhysGaussian#33]
hi, thanks for your great work! However, when i was testing ficus by setting young's module to 2e9, it reported error ：
Traceback (most recent call last):
  File "/home/swu/wzy/PhysGaussian/gs_simulation.py", line 320, in <module>
    mpm_solver.p2g2p(frame, substep_dt, device=device)
  File "/home/swu/wzy/PhysGaussian/mpm_solver_warp/mpm_solver_warp.py", line 447, in p2g2p
    wp.launch(
  File "/home/swu/anaconda3/envs/PhysGaussian/lib/python3.9/site-packages/warp/context.py", line 3220, in launch
    raise e
  File "/home/swu/anaconda3/envs/PhysGaussian/lib/python3.9/site-packages/warp/context.py", line 3217, in launch
    runtime.verify_cuda_device(device)
  File "/home/swu/anaconda3/envs/PhysGaussian/lib/python3.9/site-packages/warp/context.py", line 2422, in verify_cuda_device
    raise RuntimeError(f"CUDA error detected: {err}")
RuntimeError: CUDA error detected: 700
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
[E 07/31/24 16:52:58.820 75184] [cuda_driver.h:operator()@90] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling stream_synchronize (cuStreamSynchronize)

I set particle_impluse force as [0, 0, 0]. and it still reported the same error. I couldn't figure it out. Hope for your early reply !

**Comment by zeshunzong** [comment]
Because we use explicit timestepping, a more stiff material usually requires smaller time step size. You can try smaller dt.
